run:
  skip-dirs:
    - .tmp
    - vendor

linters:
  disable-all: true
  enable:
    # - errcheck
    - gocritic
    # - goconst
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - stylecheck
    - typecheck
    - unused

linters-settings:
  govet:
    # report about shadowed variables
    check-shadowing: true

issues:
  exclude-rules:
    # - path: _test\.go
    #   linters:
    #     - goconst

    # False positives on CGO generated code
    - linters: [staticcheck]
      text: "SA4000:"
      path: vips/*

    # False positives on CGO generated code
    - linters: [gocritic]
      text: "dupSubExpr"
      path: vips/*

    - linters: [stylecheck]
      text: "ST1005:"
