module_memory_request: "100Mi"
module_cpu_request: "15m"
module_memory_limit: "300Mi"
module_build_configuration: "Debug"
module_min_replicas: 1
module_max_replicas: 2
module_target_average_cpu_utilization: 80
module_stop_grace_period_miliseconds: 30000
module_termination_grace_period_seconds: 40
module_readiness_initial_delay_seconds: 2
module_readiness_period_seconds: 2
module_namespace: "dev"
repo_folder: "imgproxy"
repo_url: "ssh://git@github.com/carwale/imgproxy.git"
github_path: "carwale/imgproxy"
hostingDomain: "carwale.com"
module_health_check_endpoint: "/health"
isWebApplication: true
is_nginx_ingress: true
module_host_name: "imgproxy-dev"
webapp_port: 5000
imgproxy_original_bucket: "m-aeplimages-dev"
imgproxy_master_bucket: "m-aeplimagesmaster-v2-dev"
