module_memory_request: "1000Mi"
module_cpu_request: "3000m"
module_cpu_limit: "3000m"
module_memory_limit: "1000Mi"
module_build_configuration: "Release"
module_min_replicas: 2
module_max_replicas: 25
module_target_average_cpu_utilization: 70
module_stop_grace_period_miliseconds: 60000
module_termination_grace_period_seconds: 70
module_readiness_initial_delay_seconds: 2
module_readiness_period_seconds: 2
module_namespace: "production"
repo_folder: "imgproxy"
repo_url: "ssh://git@github.com/carwale/imgproxy.git"
github_path: "carwale/imgproxy"
prefixDomain: "test.imgproxy"
hostingDomain: "carwale.com"
module_health_check_endpoint: "/health"
isWebApplication: true
is_nginx_ingress: true
module_host_name: "imgproxy"
webapp_port: 5000
module_asg_name: "kubernetes-production-ms-cluster-v2-AL23"
second_host_domains:
  [
    "imgd.aeplcdn.com",
    "imgd-ct.aeplcdn.com",
    "*.aeplcdn.com",
    "img-ct.carwale.com",
    "img.carwale.com",
  ]
