repo_url: "ssh://git@github.com/carwale/imgproxy.git"
repo_folder: "imgproxy"
productionPipelineName: "imgproxy-prod"
releaseTeamName: "core-tech"
allowedComments:
    - name: ":hostOnDev"
      description: "hosts feature branch on dev env"
      options:
          - "N/A"
    - name: ":help"
      description: "Prints this comment"
      options:
          - "N/A"
    - name: ":mergeBranch"
      description: "Merge branch to base branch"
      options:
          - "--skipCodacy - skip codacy check on latest commit"
          - "--skipMutation - skip mutation check on latest commit"
          - '--reason="xyz reason" - reason is MANDATORY while using any of the skip flags'
    - name: ":runUnitTests"
      description: "Runs unit tests"
      options:
          - "N/A"
    - name: ":startRelease"
      description: ":startRelease"
      options:
          - "<ReleaseVersion> e.g. v20.5.6"
          - "<ReleaseType(regular|hotfix)(optional|default:regular)>"
    - name: ":stopBuild"
      description: ":stopBuild"
      options:
          - "<BuildNumber> e.g. 12"
          - "<Force(force)(optional)> e.g. force"
    