#!/bin/sh

if ! git diff --name-only | grep -qe ".*\.go$"; then
  echo "Nothing to lint"
  exit 0;
fi

if [ -x "$(which brew)" ]; then
  export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$(brew --prefix libffi)/lib/pkgconfig"
fi

export CGO_LDFLAGS_ALLOW="-s|-w"
export CGO_CFLAGS_ALLOW="-Xpreprocessor"

golangci-lint run
