name: Build CI Docker

on:
  workflow_dispatch:
    inputs:
      vips_versions:
        description: 'Whitespace separated list of libvips versions to build'
        required: true
        default: "8.14 8.15 8.16"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate Docker tag
        id: tag
        run: echo "tag=ghcr.io/imgproxy/imgproxy-ci:$(date +%Y%m%d%H%M)" >> "$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./.github/ci-docker/Dockerfile
          tags: ${{ steps.tag.outputs.tag }}
          platforms: linux/amd64
          build-args: |
            "VIPS_VERSIONS=${{ github.event.inputs.vips_versions }}"
          push: true
