name: Build CI Docker

on:
  workflow_dispatch:
    inputs:
      vips_versions:
        description: 'Whitespace separated list of libvips versions to build'
        required: true
        default: "8.14 8.15 8.16"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Generate Docker tag
        id: tag
        run: echo "tag=ghcr.io/imgproxy/imgproxy-ci:$(date +%Y%m%d%H%M)" >> "$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          context: .
          file: ./.github/ci-docker/Dockerfile
          tags: ${{ steps.tag.outputs.tag }}
          platforms: linux/amd64
          build-args: |
            "VIPS_VERSIONS=${{ github.event.inputs.vips_versions }}"
          push: true
