name: Go Vulnerability Check

on:
  workflow_call:
    inputs:
      container_image:
        required: true
        type: string

env:
  CGO_LDFLAGS_ALLOW: "-s|-w"
  PKG_CONFIG_LIBDIR: /opt/imgproxy/lib/pkgconfig
  LD_LIBRARY_PATH: /opt/imgproxy/lib
  GOFLAGS: -buildvcs=false

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.container_image }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download mods
        run: go mod download

      - name: Mark git workspace as safe
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Run govulncheck (symbol scan)
        run: go tool govulncheck -scan symbol ./...
